baseURL = "https://markstechnotes.github.io/MyBlog/"
languageCode = "en-us"
title = "Markâ€™s Tech Notes"
theme = "ananke"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
